version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend/Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
      - database

  backend:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Docker/database/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: