version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend/Dockerfile
    ports:
      - "8100:8100" # Default port for Ionic
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
      - database

  backend:
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/strongeryou

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: strongeryou
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
