CREATE TABLE IF NOT EXISTS Users (
    UserID SERIAL PRIMARY KEY,
    DateJoined DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS Routines (
    RoutineID SERIAL PRIMARY KEY,
    RoutineName VARCHAR(255) NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserID SMALLINT REFERENCES Users(UserID),
    ExerciseList TEXT[] NOT NULL    
);

CREATE TABLE IF NOT EXISTS ExerciseList (
    ExerciseID SERIAL PRIMARY KEY,
    ExerciseName VARCHAR(255) NOT NULL,
    MusclesTrained TEXT[] NOT NULL,
    ExerciseType VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Workout (
    WorkoutID SERIAL PRIMARY KEY,
    Start TIMESTAMP NOT NULL,
    "End" TIMESTAMP NOT NULL,
    RoutineID INTEGER REFERENCES Routines(RoutineID)
);

CREATE TABLE IF NOT EXISTS PRs (
    PRID SERIAL PRIMARY KEY,
    HeaviestWeight SMALLINT NOT NULL,
    OneRM REAL NOT NULL,
    SetVolume INTEGER NOT NULL,
    ExerciseID SMALLINT REFERENCES ExerciseList(ExerciseID),
    WorkoutID SMALLINT REFERENCES Workout(WorkoutID)
);

CREATE TABLE IF NOT EXISTS HighestRepsPerWeight (
    ID SERIAL PRIMARY KEY,
    Weight SMALLINT NOT NULL,
    HighestReps SMALLINT NOT NULL,
    ExerciseID SMALLINT REFERENCES ExerciseList(ExerciseID),
    PRID SMALLINT REFERENCES PRs(PRID)
);

CREATE TABLE IF NOT EXISTS Routines_Exercises_Sets (
    RoutineID SMALLINT REFERENCES Routines(RoutineID),
    ExerciseID SMALLINT REFERENCES ExerciseList(ExerciseID),
    NumberOfSets SMALLINT NOT NULL,
    PRIMARY KEY (RoutineID, ExerciseID)
);

CREATE TABLE IF NOT EXISTS Workout_Exercises_Sets (
    WorkoutID SMALLINT REFERENCES Workout(WorkoutID),
    ExerciseID SMALLINT REFERENCES ExerciseList(ExerciseID),
    SetID SMALLINT,
    PRIMARY KEY (WorkoutID, ExerciseID, SetID)
);

CREATE TABLE IF NOT EXISTS "Set" (
    SetID SERIAL PRIMARY KEY,
    Weight SMALLINT NOT NULL,
    Reps SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Markers (
    MarkerID SERIAL PRIMARY KEY,
    MarkerName VARCHAR(255) NOT NULL,
    Value REAL NOT NULL,
    Date DATE NOT NULL,
    UserID SMALLINT REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS MarkerList (
    MarkerID SERIAL PRIMARY KEY,
    MarkerName VARCHAR(255) NOT NULL,
    UserID SMALLINT REFERENCES Users(UserID),
    "Clr" VARCHAR(10)
);

CREATE INDEX IF NOT EXISTS idx_users_date_joined ON Users(DateJoined);

CREATE INDEX IF NOT EXISTS idx_routines_user ON Routines(UserID);

CREATE INDEX IF NOT EXISTS idx_workout_routine ON Workout(RoutineID);

CREATE INDEX IF NOT EXISTS idx_markers_user ON Markers(UserID);

CREATE INDEX IF NOT EXISTS idx_markers_date ON Markers(Date);
